platform :ios, '13.0'

target 'flash-chat' do
  use_frameworks!

  # Pods for flash-chat
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
end
